#!/usr/bin/env python

import sys

from sai_visualizer.visualizer import Visualizer
from rqt_gui.main import Main

plugin = 'sai_visualizer'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
