#!/usr/bin/env python

import sys

from rqt_visualizer.visualizer import Visualizer
from rqt_gui.main import Main

plugin = 'rqt_visualizer'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
